フィルタの項目を追加、画面左右に余白を追加
SIT-DigiCre/digicore_v3_admin pull request #6
Opened 2023-03-31 11:18 UTC by ymd1138

2023-04-01 04:59 UTC, MogamiTsuchikawa commented
フィルタすべき項目は以上ですか？本当に？？

2023-04-01 05:04 UTC, MogamiTsuchikawa requested changes
全体的に甘いです

2023-04-01 05:04 UTC, MogamiTsuchikawa commented on pages/users.tsx
> +    <div style={{ width: "90vw", margin: "auto" }} className="overflow-auto">
左右に余白を作りたいのであれば、そもそもbootstrapのcontainerなりをしっかり利用してください。使い方などはDBのページを参考にしてください。

2023-04-01 05:04 UTC, MogamiTsuchikawa commented on pages/users.tsx
> +        style={{ tableLayout: "fixed", overflow: "scroll" }}
overflowはscrollだとX,Yどちらもスクロールが出てしまいます。autoにして必要な部分だけ表示されるようにしてください

2023-04-01 09:40 UTC, MogamiTsuchikawa requested changes

2023-04-01 09:40 UTC, MogamiTsuchikawa commented on pages/users.tsx
> +          <input
このまま標準の使いにくいinput使うんですか？Bootstrapのcheckboxを利用してください。

2023-04-29 08:38 UTC, ymd1138 commented
## 概要

- [x] フィルタ項目の見直し 
- [x] チェックボックスを横並びへ
- [x] importの中括弧をもとに戻す
- [x] defaultCheckedの分岐をリファクタリング
- [x] marginをpaddingに修正
- [x] 不要なフラグメントを削除
- [x] CSSをInline Stylesに変更


## スクリーンショット
**初期状態**
![スクリーンショット 2023-04-29 1717271](https://user-images.githubusercontent.com/74826010/235292640-6c8c84b6-6fcb-40d6-a024-ddfaf79607a6.png)

**すべてチェックした状態**
![スクリーンショット 2023-04-29 171740](https://user-images.githubusercontent.com/74826010/235292641-070b860e-9744-4156-8242-82302f5ee83d.png)
![スクリーンショット 2023-04-29 171749](https://user-images.githubusercontent.com/74826010/235292643-f630236f-352f-4110-9934-948cdc2fc47f.png)

## 破壊的変更があるか(あれば内容を記載)

- [ ] YES
- [x] NO

## チェック項目

- [x] ビルドが通る
- [x] 作成した機能が想定通りに動作する
- [x] スマートフォンサイズで表示確認を行った
- [x] ダークモードで表示確認を行った
- [x] warning が増えていない
- [ ] 複雑なコードにはコメントを記載してある

2023-04-30 14:03 UTC, MogamiTsuchikawa requested changes
まだ実際に動作確認はできていませんが、とりあえずコードで気になるところだけ

2023-04-30 14:03 UTC, MogamiTsuchikawa commented on pages/users.tsx
> +  /* あとでオブジェクトのリストに書き換えます */
変なメモを残さないでください

2023-04-30 14:03 UTC, MogamiTsuchikawa commented on pages/users.tsx
> +  width: "100px",
pxをつけるかつけないかで、統一をお願いします

2023-05-01 08:39 UTC, MogamiTsuchikawa requested changes

2023-05-01 08:39 UTC, MogamiTsuchikawa commented on pages/users.tsx
> +                    <th style={{ width: "100px" }}>Discord ID</th>
DiscordIDが入っているとはみ出す
![image](https://user-images.githubusercontent.com/30793866/235429988-6872173d-6f87-43ee-823f-8a3a442994bf.png)

2023-05-01 08:48 UTC, MogamiTsuchikawa approved these changes
リリースも遅れていて早めにリリースしたいとのことなのでこちらで修正してしまいました。最後にそちらで一度動作確認を取った後にMergeしちゃってください

2023-05-02 05:28 UTC, merged